#!/bin/bash

COLOR_WHITE='\033[0;37m'
COLOR_B_PURPLE='\033[1;35m'
COLOR_DEFAULT='\033[0m'

function logger {
    echo -e "${COLOR_B_PURPLE}[creamov:dotfiles]:${COLOR_WHITE} $1${COLOR_DEFAULT}"
}

logger "Creating symlinks for vim..."
ln -sf $(pwd)/src/vimrc $HOME/.vimrc
ln -sf $(pwd)/src/tmux.conf $HOME/.tmux.conf

logger "Installing vim-plug and do PlugInstall..."
vim

logger "Job's done! ;)"
