#!/bin/bash

COLOR_WHITE='\033[0;37m'
COLOR_B_PURPLE='\033[1;35m'
COLOR_DEFAULT='\033[0m'

function logger {
    echo -e "${COLOR_B_PURPLE}[creamov:dotfiles]:${COLOR_WHITE} $1${COLOR_DEFAULT}"
}

logger "Creating symlinks for vim, tmux and git..."

mkdir -p $HOME/.config/nvim
ln -sf $(pwd)/src/nvim/init.vim $HOME/.config/nvim/init.vim
ln -sf $(pwd)/src/nvim/init.vim $HOME/.vimrc

# ln -sf $(pwd)/src/vimrc $HOME/.vimrc
ln -sf $(pwd)/src/zshrc $HOME/.zshrc
ln -sf $(pwd)/src/ssh_config $HOME/.ssh/config
ln -sf $(pwd)/src/zhistory $HOME/.zhistory
ln -sf $(pwd)/src/tmux.conf $HOME/.tmux.conf
ln -sf $(pwd)/src/gitconfig $HOME/.gitconfig

# don't forget to delete default .zpreztorc link after installation
ln -sf $(pwd)/src/zpreztorc $HOME/.zpreztorc

logger "Create undo-dir for vim..."
mkdir -p $HOME/.vim/undo-dir

logger "Installing vim-plug and do PlugInstall..."
vim

DEFAULT_THEME=base16_default-dark
logger "Try to set ${DEFAULT_THEME}"
eval $DEFAULT_THEME

logger "Job's done! ;)"
